name: renta
description: Rental app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #For Dot indicator in pageView
  smooth_page_indicator: ^1.0.0+2

  #For Star rating
  smooth_star_rating_null_safety: ^1.0.4+2

  #For Country code picker
  country_calling_code_picker: ^2.0.1

  intl: ^0.17.0

  #mobX
  mobx:
  flutter_mobx:

  #shared preference
  shared_preferences: ^2.0.15

  cupertino_icons: ^1.0.5
  email_validator: ^2.1.17
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
  loader_overlay: ^2.2.0
  top_snackbar_flutter: ^3.0.0+1
  image_picker: ^0.8.7+2
  firebase_storage: ^11.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  mobx_codegen:
  flutter_launcher_icons: "^0.13.0"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
